/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagelibrary;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import java.awt.image.BufferedImage;

/**
 *
 * @author Ibraheem Saleh
 */
public class ImageLibraryUI extends javax.swing.JFrame {

    BufferedImage leftImage;
    BufferedImage rightImage;
    /**
     * Creates new form ImageLibraryUI
     */
    public ImageLibraryUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        changeResolutionChooser = new javax.swing.JDialog();
        changeResolutionAcceptButton = new javax.swing.JButton();
        changeResolutionCancelButton = new javax.swing.JButton();
        interpolationMethodChoice = new java.awt.Choice();
        jLabel1 = new javax.swing.JLabel();
        changeResolutionWidth = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        changeResolutionHeight = new java.awt.TextField();
        selectBitplaneChooser = new javax.swing.JDialog();
        selectBitplaneAcceptButton = new javax.swing.JButton();
        selectBitplaneDepthCancelButton = new javax.swing.JButton();
        selectBitplaneField = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        changePixelDepthChooser = new javax.swing.JDialog();
        changePixelDepthAcceptButton = new javax.swing.JButton();
        changePixelDepthCancelButton = new javax.swing.JButton();
        changePixelDepthField = new java.awt.TextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        histogramEqualizationChooser = new javax.swing.JDialog();
        histogramEqualizationAcceptButton = new javax.swing.JButton();
        histogramEqualizationCancelButton = new javax.swing.JButton();
        equalizationMethodChoice = new java.awt.Choice();
        jLabel5 = new javax.swing.JLabel();
        histogramEqualizationFilterX = new java.awt.TextField();
        histogramEqualizationFilterY = new java.awt.TextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        histogramEqualizationEdgePixelChoice = new java.awt.Choice();
        jLabel13 = new javax.swing.JLabel();
        spatialFilteringChooser = new javax.swing.JDialog();
        spatialFilteringAcceptButton = new javax.swing.JButton();
        spatialFilteringCancelButton = new javax.swing.JButton();
        spatialFilterMethodChoice = new java.awt.Choice();
        jLabel14 = new javax.swing.JLabel();
        spatialFilterX = new java.awt.TextField();
        spatialFilterY = new java.awt.TextField();
        spatialFilteringScalar = new java.awt.TextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        spatialFilteringEdgePixelChoice = new java.awt.Choice();
        selectBitplanesChooser = new javax.swing.JDialog();
        selectBitplanesAcceptButton = new javax.swing.JButton();
        selectBitplanesCancelButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        bit8CheckBox = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        bit7CheckBox = new javax.swing.JCheckBox();
        bit6CheckBox = new javax.swing.JCheckBox();
        bit5CheckBox = new javax.swing.JCheckBox();
        bit4CheckBox = new javax.swing.JCheckBox();
        bit1CheckBox = new javax.swing.JCheckBox();
        bit2CheckBox = new javax.swing.JCheckBox();
        bit3CheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        leftImageLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        rightImageLabel = new javax.swing.JLabel();
        acceptTransformationButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openImage = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        transformMenu = new javax.swing.JMenu();
        changeResolutionMenu = new javax.swing.JMenuItem();
        changePixelDepthMenu = new javax.swing.JMenuItem();
        selectBitplaneMenu = new javax.swing.JMenuItem();
        selectBitplanesMenu = new javax.swing.JMenuItem();
        histogramEqualizationMenu = new javax.swing.JMenuItem();
        drawHistogramMenu = new javax.swing.JMenuItem();
        spatialFilteringMenu = new javax.swing.JMenuItem();

        fileChooser.setCurrentDirectory(new File("./images"));

        changeResolutionChooser.setMinimumSize(new java.awt.Dimension(600, 300));

        changeResolutionAcceptButton.setText("Accept");
        changeResolutionAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeResolutionAcceptButtonActionPerformed(evt);
            }
        });

        changeResolutionCancelButton.setText("Close");
        changeResolutionCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeResolutionCancelButtonActionPerformed(evt);
            }
        });

        interpolationMethodChoice.add("Nearest Neighbor");
        interpolationMethodChoice.add("LinearX");
        interpolationMethodChoice.add("LinearY");
        interpolationMethodChoice.add("Bilinear");
        interpolationMethodChoice.select("Nearest Neighbor");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Select Interpolation Method:");

        changeResolutionWidth.setMinimumSize(new java.awt.Dimension(100, 20));
        changeResolutionWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeResolutionWidthActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Input New Image Width (px):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Change Resolution Menu");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Input New Image Height (px):");

        changeResolutionHeight.setMinimumSize(new java.awt.Dimension(100, 20));
        changeResolutionHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeResolutionHeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeResolutionChooserLayout = new javax.swing.GroupLayout(changeResolutionChooser.getContentPane());
        changeResolutionChooser.getContentPane().setLayout(changeResolutionChooserLayout);
        changeResolutionChooserLayout.setHorizontalGroup(
            changeResolutionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeResolutionChooserLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(changeResolutionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeResolutionChooserLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(changeResolutionChooserLayout.createSequentialGroup()
                        .addGroup(changeResolutionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(changeResolutionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interpolationMethodChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeResolutionWidth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeResolutionHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(changeResolutionChooserLayout.createSequentialGroup()
                .addGroup(changeResolutionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeResolutionChooserLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel3))
                    .addGroup(changeResolutionChooserLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(changeResolutionAcceptButton)
                        .addGap(29, 29, 29)
                        .addComponent(changeResolutionCancelButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changeResolutionChooserLayout.setVerticalGroup(
            changeResolutionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeResolutionChooserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(changeResolutionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeResolutionWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(changeResolutionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeResolutionHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(changeResolutionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interpolationMethodChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(changeResolutionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeResolutionAcceptButton)
                    .addComponent(changeResolutionCancelButton))
                .addContainerGap())
        );

        selectBitplaneChooser.setMaximumSize(new java.awt.Dimension(450, 200));
        selectBitplaneChooser.setMinimumSize(new java.awt.Dimension(450, 200));

        selectBitplaneAcceptButton.setText("Accept");
        selectBitplaneAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBitplaneAcceptButtonActionPerformed(evt);
            }
        });

        selectBitplaneDepthCancelButton.setText("Close");
        selectBitplaneDepthCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBitplaneDepthCancelButtonActionPerformed(evt);
            }
        });

        selectBitplaneField.setMinimumSize(new java.awt.Dimension(100, 20));
        selectBitplaneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBitplaneFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Select Pixel Bitplane Slice (bit):");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Select Bitplane Menu");

        javax.swing.GroupLayout selectBitplaneChooserLayout = new javax.swing.GroupLayout(selectBitplaneChooser.getContentPane());
        selectBitplaneChooser.getContentPane().setLayout(selectBitplaneChooserLayout);
        selectBitplaneChooserLayout.setHorizontalGroup(
            selectBitplaneChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectBitplaneChooserLayout.createSequentialGroup()
                .addGroup(selectBitplaneChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectBitplaneChooserLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(selectBitplaneAcceptButton)
                        .addGap(87, 87, 87)
                        .addComponent(selectBitplaneDepthCancelButton))
                    .addGroup(selectBitplaneChooserLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(selectBitplaneChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(selectBitplaneChooserLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectBitplaneField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        selectBitplaneChooserLayout.setVerticalGroup(
            selectBitplaneChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectBitplaneChooserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(selectBitplaneChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectBitplaneField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36)
                .addGroup(selectBitplaneChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectBitplaneAcceptButton)
                    .addComponent(selectBitplaneDepthCancelButton))
                .addContainerGap())
        );

        changePixelDepthChooser.setMaximumSize(new java.awt.Dimension(450, 200));
        changePixelDepthChooser.setMinimumSize(new java.awt.Dimension(450, 200));

        changePixelDepthAcceptButton.setText("Accept");
        changePixelDepthAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePixelDepthAcceptButtonActionPerformed(evt);
            }
        });

        changePixelDepthCancelButton.setText("Close");
        changePixelDepthCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePixelDepthCancelButtonActionPerformed(evt);
            }
        });

        changePixelDepthField.setMinimumSize(new java.awt.Dimension(100, 20));
        changePixelDepthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePixelDepthFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Select Pixel Bit Depth (bit):");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Change Pixel Depth Menu");

        javax.swing.GroupLayout changePixelDepthChooserLayout = new javax.swing.GroupLayout(changePixelDepthChooser.getContentPane());
        changePixelDepthChooser.getContentPane().setLayout(changePixelDepthChooserLayout);
        changePixelDepthChooserLayout.setHorizontalGroup(
            changePixelDepthChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePixelDepthChooserLayout.createSequentialGroup()
                .addGroup(changePixelDepthChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePixelDepthChooserLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(changePixelDepthAcceptButton)
                        .addGap(87, 87, 87)
                        .addComponent(changePixelDepthCancelButton))
                    .addGroup(changePixelDepthChooserLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(changePixelDepthChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(changePixelDepthChooserLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(changePixelDepthField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changePixelDepthChooserLayout.setVerticalGroup(
            changePixelDepthChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePixelDepthChooserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(changePixelDepthChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePixelDepthField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(changePixelDepthChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePixelDepthAcceptButton)
                    .addComponent(changePixelDepthCancelButton))
                .addContainerGap())
        );

        histogramEqualizationChooser.setMinimumSize(new java.awt.Dimension(600, 300));

        histogramEqualizationAcceptButton.setText("Accept");
        histogramEqualizationAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histogramEqualizationAcceptButtonActionPerformed(evt);
            }
        });

        histogramEqualizationCancelButton.setText("Close");
        histogramEqualizationCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histogramEqualizationCancelButtonActionPerformed(evt);
            }
        });

        equalizationMethodChoice.add("Global Histogram Equalization");
        equalizationMethodChoice.add("Local Histogram Equalization");
        equalizationMethodChoice.select("Local Histogram Equalization");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Select Histogram Equalization Method:");

        histogramEqualizationFilterX.setMinimumSize(new java.awt.Dimension(100, 20));
        histogramEqualizationFilterX.setText("3");
        histogramEqualizationFilterX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histogramEqualizationFilterXActionPerformed(evt);
            }
        });

        histogramEqualizationFilterY.setMinimumSize(new java.awt.Dimension(100, 20));
        histogramEqualizationFilterY.setText("3");
        histogramEqualizationFilterY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histogramEqualizationFilterYActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Filter Size (Local Histogram Equalization Only)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Histogram Equalization Menu");

        jLabel12.setText("x");

        histogramEqualizationEdgePixelChoice.add("Zero Padding");
        histogramEqualizationEdgePixelChoice.add("Skip Edge Pixel Processing");
        histogramEqualizationEdgePixelChoice.select("Zero Padding");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Select Edge Pixel Handling Method:");

        javax.swing.GroupLayout histogramEqualizationChooserLayout = new javax.swing.GroupLayout(histogramEqualizationChooser.getContentPane());
        histogramEqualizationChooser.getContentPane().setLayout(histogramEqualizationChooserLayout);
        histogramEqualizationChooserLayout.setHorizontalGroup(
            histogramEqualizationChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, histogramEqualizationChooserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(143, 143, 143))
            .addGroup(histogramEqualizationChooserLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(histogramEqualizationAcceptButton)
                .addGap(29, 29, 29)
                .addComponent(histogramEqualizationCancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(histogramEqualizationChooserLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(histogramEqualizationChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(histogramEqualizationChooserLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(histogramEqualizationEdgePixelChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(histogramEqualizationChooserLayout.createSequentialGroup()
                        .addGroup(histogramEqualizationChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(histogramEqualizationChooserLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27))
                            .addGroup(histogramEqualizationChooserLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(histogramEqualizationChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equalizationMethodChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(histogramEqualizationChooserLayout.createSequentialGroup()
                                .addComponent(histogramEqualizationFilterX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(histogramEqualizationFilterY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))))
        );
        histogramEqualizationChooserLayout.setVerticalGroup(
            histogramEqualizationChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(histogramEqualizationChooserLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(histogramEqualizationChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(histogramEqualizationChooserLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(histogramEqualizationChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(equalizationMethodChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(histogramEqualizationChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(histogramEqualizationFilterX, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(histogramEqualizationFilterY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(histogramEqualizationChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(histogramEqualizationEdgePixelChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(histogramEqualizationChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(histogramEqualizationAcceptButton)
                    .addComponent(histogramEqualizationCancelButton))
                .addContainerGap())
        );

        spatialFilteringChooser.setMinimumSize(new java.awt.Dimension(600, 300));

        spatialFilteringAcceptButton.setText("Accept");
        spatialFilteringAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatialFilteringAcceptButtonActionPerformed(evt);
            }
        });

        spatialFilteringCancelButton.setText("Close");
        spatialFilteringCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatialFilteringCancelButtonActionPerformed(evt);
            }
        });

        spatialFilterMethodChoice.add("Smoothing Filter");
        spatialFilterMethodChoice.add("Median Filter");
        spatialFilterMethodChoice.add("Sharpening Laplacian Filter");
        spatialFilterMethodChoice.add("High-Boosting Filter");
        spatialFilterMethodChoice.select("Median Filter");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Select Filter Type:");

        spatialFilterX.setMinimumSize(new java.awt.Dimension(100, 20));
        spatialFilterX.setText("3");
        spatialFilterX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatialFilterXActionPerformed(evt);
            }
        });

        spatialFilterY.setMinimumSize(new java.awt.Dimension(100, 20));
        spatialFilterY.setText("3");
        spatialFilterY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatialFilterYActionPerformed(evt);
            }
        });

        spatialFilteringScalar.setMinimumSize(new java.awt.Dimension(100, 20));
        spatialFilteringScalar.setText("1.2");
        spatialFilteringScalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatialFilteringScalarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Filter Size:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Spatial Filtering Menu");

        jLabel17.setText("x");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Filter Scalar (High-Boosting Filter Only):");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Select Edge Pixel Handling Method:");

        spatialFilteringEdgePixelChoice.add("Zero Padding");
        spatialFilteringEdgePixelChoice.select("Zero Padding");

        javax.swing.GroupLayout spatialFilteringChooserLayout = new javax.swing.GroupLayout(spatialFilteringChooser.getContentPane());
        spatialFilteringChooser.getContentPane().setLayout(spatialFilteringChooserLayout);
        spatialFilteringChooserLayout.setHorizontalGroup(
            spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                .addGroup(spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(spatialFilteringAcceptButton)
                        .addGap(29, 29, 29)
                        .addComponent(spatialFilteringCancelButton))
                    .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spatialFilteringEdgePixelChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spatialFilteringScalar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                        .addGroup(spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                .addGap(27, 27, 27))
                            .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spatialFilterMethodChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                                .addComponent(spatialFilterX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spatialFilterY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))))
        );
        spatialFilteringChooserLayout.setVerticalGroup(
            spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spatialFilteringChooserLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spatialFilterMethodChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spatialFilterX, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(spatialFilterY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(spatialFilteringScalar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spatialFilteringEdgePixelChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spatialFilteringChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spatialFilteringAcceptButton)
                    .addComponent(spatialFilteringCancelButton))
                .addContainerGap())
        );

        selectBitplanesChooser.setMaximumSize(new java.awt.Dimension(450, 200));
        selectBitplanesChooser.setMinimumSize(new java.awt.Dimension(450, 200));

        selectBitplanesAcceptButton.setText("Accept");
        selectBitplanesAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBitplanesAcceptButtonActionPerformed(evt);
            }
        });

        selectBitplanesCancelButton.setText("Close");
        selectBitplanesCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBitplanesCancelButtonActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("Select Bitplanes Menu");

        bit8CheckBox.setText("Bit 8");
        bit8CheckBox.setSelected(true);
        bit8CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bit8CheckBoxActionPerformed(evt);
            }
        });

        jLabel20.setText("Select which bits to enable/disable:");

        bit7CheckBox.setText("Bit 7");
        bit7CheckBox.setSelected(true);
        bit7CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bit7CheckBoxActionPerformed(evt);
            }
        });

        bit6CheckBox.setText("Bit 6");
        bit6CheckBox.setSelected(true);
        bit6CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bit6CheckBoxActionPerformed(evt);
            }
        });

        bit5CheckBox.setText("Bit 5");
        bit5CheckBox.setSelected(true);
        bit5CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bit5CheckBoxActionPerformed(evt);
            }
        });

        bit4CheckBox.setText("Bit 4");
        bit4CheckBox.setSelected(true);
        bit4CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bit4CheckBoxActionPerformed(evt);
            }
        });

        bit1CheckBox.setText("Bit 1");
        bit1CheckBox.setSelected(true);
        bit1CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bit1CheckBoxActionPerformed(evt);
            }
        });

        bit2CheckBox.setText("Bit 2");
        bit2CheckBox.setSelected(true);
        bit2CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bit2CheckBoxActionPerformed(evt);
            }
        });

        bit3CheckBox.setText("Bit 3");
        bit3CheckBox.setSelected(true);
        bit3CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bit3CheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectBitplanesChooserLayout = new javax.swing.GroupLayout(selectBitplanesChooser.getContentPane());
        selectBitplanesChooser.getContentPane().setLayout(selectBitplanesChooserLayout);
        selectBitplanesChooserLayout.setHorizontalGroup(
            selectBitplanesChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectBitplanesChooserLayout.createSequentialGroup()
                .addGroup(selectBitplanesChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectBitplanesChooserLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(selectBitplanesAcceptButton)
                        .addGap(87, 87, 87)
                        .addComponent(selectBitplanesCancelButton)
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectBitplanesChooserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(selectBitplanesChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(selectBitplanesChooserLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(selectBitplanesChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(selectBitplanesChooserLayout.createSequentialGroup()
                                        .addComponent(bit8CheckBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(bit7CheckBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(bit6CheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bit5CheckBox))
                                    .addGroup(selectBitplanesChooserLayout.createSequentialGroup()
                                        .addComponent(bit4CheckBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(bit3CheckBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(bit2CheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bit1CheckBox))))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        selectBitplanesChooserLayout.setVerticalGroup(
            selectBitplanesChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectBitplanesChooserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(selectBitplanesChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bit8CheckBox)
                    .addComponent(bit7CheckBox)
                    .addComponent(bit6CheckBox)
                    .addComponent(bit5CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(selectBitplanesChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bit4CheckBox)
                    .addComponent(bit3CheckBox)
                    .addComponent(bit2CheckBox)
                    .addComponent(bit1CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(selectBitplanesChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectBitplanesAcceptButton)
                    .addComponent(selectBitplanesCancelButton))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(leftImageLabel);
        leftImageLabel.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        leftImageLabel.setVerticalAlignment(javax.swing.JLabel.CENTER);

        jScrollPane2.setViewportView(rightImageLabel);
        rightImageLabel.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        rightImageLabel.setVerticalAlignment(javax.swing.JLabel.CENTER);

        acceptTransformationButton.setText("Accept Transformation");
        acceptTransformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptTransformationButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        openImage.setText("Open Image");
        openImage.setToolTipText("");
        openImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openImageActionPerformed(evt);
            }
        });
        fileMenu.add(openImage);
        openImage.getAccessibleContext().setAccessibleName("openImageMenu");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        fileMenu.add(exit);

        jMenuBar1.add(fileMenu);
        fileMenu.getAccessibleContext().setAccessibleDescription("");

        transformMenu.setText("Transform");
        transformMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformMenuActionPerformed(evt);
            }
        });

        changeResolutionMenu.setText("Change Resolution");
        changeResolutionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeResolutionMenuActionPerformed(evt);
            }
        });
        transformMenu.add(changeResolutionMenu);

        changePixelDepthMenu.setText("Change Pixel Depth");
        changePixelDepthMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePixelDepthMenuActionPerformed(evt);
            }
        });
        transformMenu.add(changePixelDepthMenu);

        selectBitplaneMenu.setText("Select Bitplane");
        selectBitplaneMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBitplaneMenuActionPerformed(evt);
            }
        });
        transformMenu.add(selectBitplaneMenu);

        selectBitplanesMenu.setText("Select Bitplanes");
        selectBitplanesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBitplanesMenuActionPerformed(evt);
            }
        });
        transformMenu.add(selectBitplanesMenu);

        histogramEqualizationMenu.setText("Histogram Equalization");
        histogramEqualizationMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histogramEqualizationMenuActionPerformed(evt);
            }
        });
        transformMenu.add(histogramEqualizationMenu);

        drawHistogramMenu.setText("Draw Histogram");
        drawHistogramMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawHistogramMenuActionPerformed(evt);
            }
        });
        transformMenu.add(drawHistogramMenu);

        spatialFilteringMenu.setText("Spatial Filtering");
        spatialFilteringMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatialFilteringMenuActionPerformed(evt);
            }
        });
        transformMenu.add(spatialFilteringMenu);

        jMenuBar1.add(transformMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acceptTransformationButton)
                .addGap(455, 455, 455))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(acceptTransformationButton))
        );

        acceptTransformationButton.getAccessibleContext().setAccessibleName("acceptButton");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptTransformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptTransformationButtonActionPerformed
        leftImage = ImageLibrary.deepCopy(rightImage);
        leftImageLabel.setIcon(new javax.swing.ImageIcon(leftImage));
    }//GEN-LAST:event_acceptTransformationButtonActionPerformed

    private void transformMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transformMenuActionPerformed

    private void openImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openImageActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                leftImage = ImageLibrary.loadGrayscaleImage(fileChooser.getSelectedFile());
                rightImage = ImageLibrary.loadGrayscaleImage(fileChooser.getSelectedFile());
                leftImageLabel.setIcon(new javax.swing.ImageIcon(leftImage));
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
              // What to do with the file, e.g. display it in a TextArea
              //textarea.read( new FileReader( file.getAbsolutePath() ), null );
            } catch (Exception ex) {
              System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_openImageActionPerformed

    private void changeResolutionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeResolutionMenuActionPerformed
        if(leftImage != null){
            changeResolutionWidth.setText(leftImage.getWidth()+"");
            changeResolutionHeight.setText(leftImage.getHeight()+"");
        }
        changeResolutionChooser.setVisible(true);
    }//GEN-LAST:event_changeResolutionMenuActionPerformed

    private void changeResolutionCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeResolutionCancelButtonActionPerformed
        changeResolutionChooser.setVisible(false);
    }//GEN-LAST:event_changeResolutionCancelButtonActionPerformed

    private void changeResolutionWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeResolutionWidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeResolutionWidthActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void changeResolutionAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeResolutionAcceptButtonActionPerformed
        int newWidth = Integer.parseInt(changeResolutionWidth.getText());
        int newHeight = Integer.parseInt(changeResolutionHeight.getText());
        switch (interpolationMethodChoice.getSelectedItem()){
            case "Nearest Neighbor":
                rightImage = ImageLibrary.nearestNeighborInterpolation(leftImage,newWidth,newHeight);
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
                //changeResolutionChooser.setVisible(false);
                break;
            case "LinearX":
                rightImage = ImageLibrary.linearInterpolationX(leftImage,newWidth,newHeight);
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
                break;
            case "LinearY":
                rightImage = ImageLibrary.linearInterpolationY(leftImage,newWidth,newHeight);
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
                break;
            case "Bilinear":
                rightImage = ImageLibrary.bilinearInterpolation(leftImage,newWidth,newHeight);
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_changeResolutionAcceptButtonActionPerformed

    private void selectBitplaneAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBitplaneAcceptButtonActionPerformed
        int newDepth = Integer.parseInt(selectBitplaneField.getText());
        rightImage = ImageLibrary.selectBitplane(leftImage, newDepth);
        rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
    }//GEN-LAST:event_selectBitplaneAcceptButtonActionPerformed

    private void selectBitplaneDepthCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBitplaneDepthCancelButtonActionPerformed
        selectBitplaneChooser.setVisible(false);
    }//GEN-LAST:event_selectBitplaneDepthCancelButtonActionPerformed

    private void selectBitplaneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBitplaneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectBitplaneFieldActionPerformed

    private void selectBitplaneMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBitplaneMenuActionPerformed
        selectBitplaneChooser.setVisible(true);
    }//GEN-LAST:event_selectBitplaneMenuActionPerformed

    private void changePixelDepthMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePixelDepthMenuActionPerformed
        changePixelDepthChooser.setVisible(true);
    }//GEN-LAST:event_changePixelDepthMenuActionPerformed

    private void changePixelDepthAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePixelDepthAcceptButtonActionPerformed
        int newDepth = Integer.parseInt(changePixelDepthField.getText());
        rightImage = ImageLibrary.changeBitDepth(leftImage, newDepth);
        rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
    }//GEN-LAST:event_changePixelDepthAcceptButtonActionPerformed

    private void changePixelDepthCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePixelDepthCancelButtonActionPerformed
        changePixelDepthChooser.setVisible(false);
    }//GEN-LAST:event_changePixelDepthCancelButtonActionPerformed

    private void changePixelDepthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePixelDepthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changePixelDepthFieldActionPerformed

    private void histogramEqualizationMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histogramEqualizationMenuActionPerformed
        histogramEqualizationChooser.setVisible(true);
    }//GEN-LAST:event_histogramEqualizationMenuActionPerformed

    private void changeResolutionHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeResolutionHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeResolutionHeightActionPerformed

    private void histogramEqualizationFilterYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histogramEqualizationFilterYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_histogramEqualizationFilterYActionPerformed

    private void histogramEqualizationFilterXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histogramEqualizationFilterXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_histogramEqualizationFilterXActionPerformed

    private void histogramEqualizationCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histogramEqualizationCancelButtonActionPerformed
        histogramEqualizationChooser.setVisible(false);
    }//GEN-LAST:event_histogramEqualizationCancelButtonActionPerformed

    private void histogramEqualizationAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histogramEqualizationAcceptButtonActionPerformed
        switch (equalizationMethodChoice.getSelectedItem()){
            case "Global Histogram Equalization":
                rightImage = ImageLibrary.histogramEqualization(leftImage);
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
                break;
            case "Local Histogram Equalization":
                String paddingType = histogramEqualizationEdgePixelChoice.getSelectedItem();
                if (paddingType == "Zero Padding")
                    paddingType = "zero";
                else
                    paddingType = "skip";
                rightImage = ImageLibrary.localHistogramEqualization(leftImage,Integer.parseInt(histogramEqualizationFilterX.getText()),Integer.parseInt(histogramEqualizationFilterY.getText()),paddingType);
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_histogramEqualizationAcceptButtonActionPerformed

    private void spatialFilteringMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatialFilteringMenuActionPerformed
        spatialFilteringChooser.setVisible(true);
    }//GEN-LAST:event_spatialFilteringMenuActionPerformed

    private void spatialFilteringAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatialFilteringAcceptButtonActionPerformed
        
        //Translate the padding type selection to the expected padding selectors
        String paddingType = spatialFilteringEdgePixelChoice.getSelectedItem();
        if (paddingType == "Zero Padding")
            paddingType = "zero";
        else
            paddingType = "skip";
        
        
        switch(spatialFilterMethodChoice.getSelectedItem()){
            case "Smoothing Filter":
                rightImage = ImageLibrary.smoothingFilter(leftImage,ImageLibrary.smoothingAverageFilter1(),paddingType);
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
                break;
            case "Median Filter":
                rightImage = ImageLibrary.medianFilter(leftImage,Integer.parseInt(spatialFilterX.getText()),Integer.parseInt(spatialFilterY.getText()),paddingType);
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
                break;
            case "Sharpening Laplacian Filter":
                rightImage = ImageLibrary.sharpeningLaplacianFilter(leftImage,Integer.parseInt(spatialFilterX.getText()),Integer.parseInt(spatialFilterY.getText()),paddingType);
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
                break;
            case "High-Boosting Filter":
                rightImage = ImageLibrary.highBoostFilter(leftImage,Integer.parseInt(spatialFilterX.getText()),Integer.parseInt(spatialFilterY.getText()),Float.parseFloat(spatialFilteringScalar.getText()),paddingType);
                rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_spatialFilteringAcceptButtonActionPerformed

    private void spatialFilteringCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatialFilteringCancelButtonActionPerformed
        spatialFilteringChooser.setVisible(false);
    }//GEN-LAST:event_spatialFilteringCancelButtonActionPerformed

    private void spatialFilterXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatialFilterXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spatialFilterXActionPerformed

    private void spatialFilterYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatialFilterYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spatialFilterYActionPerformed

    private void spatialFilteringScalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatialFilteringScalarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spatialFilteringScalarActionPerformed

    private void selectBitplanesAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBitplanesAcceptButtonActionPerformed
        rightImage = ImageLibrary.selectBitplanes(leftImage,bit8CheckBox.isSelected(),bit7CheckBox.isSelected(),bit6CheckBox.isSelected(),bit5CheckBox.isSelected(),bit4CheckBox.isSelected(),bit3CheckBox.isSelected(),bit2CheckBox.isSelected(),bit1CheckBox.isSelected());
        rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
    }//GEN-LAST:event_selectBitplanesAcceptButtonActionPerformed

    private void selectBitplanesCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBitplanesCancelButtonActionPerformed
        selectBitplanesChooser.setVisible(false);
    }//GEN-LAST:event_selectBitplanesCancelButtonActionPerformed

    private void bit8CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bit8CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bit8CheckBoxActionPerformed

    private void bit7CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bit7CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bit7CheckBoxActionPerformed

    private void bit6CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bit6CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bit6CheckBoxActionPerformed

    private void bit5CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bit5CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bit5CheckBoxActionPerformed

    private void bit4CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bit4CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bit4CheckBoxActionPerformed

    private void bit1CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bit1CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bit1CheckBoxActionPerformed

    private void bit2CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bit2CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bit2CheckBoxActionPerformed

    private void bit3CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bit3CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bit3CheckBoxActionPerformed

    private void selectBitplanesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBitplanesMenuActionPerformed
        selectBitplanesChooser.setVisible(true);
    }//GEN-LAST:event_selectBitplanesMenuActionPerformed

    private void drawHistogramMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawHistogramMenuActionPerformed
        rightImage = ImageLibrary.drawHistogram(leftImage, 768, 512);
        rightImageLabel.setIcon(new javax.swing.ImageIcon(rightImage));
    }//GEN-LAST:event_drawHistogramMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageLibraryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptTransformationButton;
    private javax.swing.JCheckBox bit1CheckBox;
    private javax.swing.JCheckBox bit2CheckBox;
    private javax.swing.JCheckBox bit3CheckBox;
    private javax.swing.JCheckBox bit4CheckBox;
    private javax.swing.JCheckBox bit5CheckBox;
    private javax.swing.JCheckBox bit6CheckBox;
    private javax.swing.JCheckBox bit7CheckBox;
    private javax.swing.JCheckBox bit8CheckBox;
    private javax.swing.JButton changePixelDepthAcceptButton;
    private javax.swing.JButton changePixelDepthCancelButton;
    private javax.swing.JDialog changePixelDepthChooser;
    private java.awt.TextField changePixelDepthField;
    private javax.swing.JMenuItem changePixelDepthMenu;
    private javax.swing.JButton changeResolutionAcceptButton;
    private javax.swing.JButton changeResolutionCancelButton;
    private javax.swing.JDialog changeResolutionChooser;
    private java.awt.TextField changeResolutionHeight;
    private javax.swing.JMenuItem changeResolutionMenu;
    private java.awt.TextField changeResolutionWidth;
    private javax.swing.JMenuItem drawHistogramMenu;
    private java.awt.Choice equalizationMethodChoice;
    private javax.swing.JMenuItem exit;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton histogramEqualizationAcceptButton;
    private javax.swing.JButton histogramEqualizationCancelButton;
    private javax.swing.JDialog histogramEqualizationChooser;
    private java.awt.Choice histogramEqualizationEdgePixelChoice;
    private java.awt.TextField histogramEqualizationFilterX;
    private java.awt.TextField histogramEqualizationFilterY;
    private javax.swing.JMenuItem histogramEqualizationMenu;
    private java.awt.Choice interpolationMethodChoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel leftImageLabel;
    private javax.swing.JMenuItem openImage;
    private javax.swing.JLabel rightImageLabel;
    private javax.swing.JButton selectBitplaneAcceptButton;
    private javax.swing.JDialog selectBitplaneChooser;
    private javax.swing.JButton selectBitplaneDepthCancelButton;
    private java.awt.TextField selectBitplaneField;
    private javax.swing.JMenuItem selectBitplaneMenu;
    private javax.swing.JButton selectBitplanesAcceptButton;
    private javax.swing.JButton selectBitplanesCancelButton;
    private javax.swing.JDialog selectBitplanesChooser;
    private javax.swing.JMenuItem selectBitplanesMenu;
    private java.awt.Choice spatialFilterMethodChoice;
    private java.awt.TextField spatialFilterX;
    private java.awt.TextField spatialFilterY;
    private javax.swing.JButton spatialFilteringAcceptButton;
    private javax.swing.JButton spatialFilteringCancelButton;
    private javax.swing.JDialog spatialFilteringChooser;
    private java.awt.Choice spatialFilteringEdgePixelChoice;
    private javax.swing.JMenuItem spatialFilteringMenu;
    private java.awt.TextField spatialFilteringScalar;
    private javax.swing.JMenu transformMenu;
    // End of variables declaration//GEN-END:variables
}
